[workspace] 
members = [ 
    "contracts/bs721-account",
    "contracts/bs721-account-minter",
    "contracts/bs721-account-marketplace",
    "packages/*",
    "scripts",
    ]
# exclude = [
#   "scripts"
# ]

resolver = "2"

[workspace.package]
version = "0.2.0"
authors = [
  "Hard-nett <hardnettt@proton.me>",
]
edition = "2021"
homepage   = "https://bitsong.io"
repository = "https://github.com/bitsongofficial/bs-accounts"
license    = "Apache-2.0"

[workspace.dependencies]
bs721                        = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "1e50abdac4517bcdd5e03491589bdba6929806cf" }
bs721-base                   = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "1e50abdac4517bcdd5e03491589bdba6929806cf"}
bs-controllers               = { library = "bs-controllers", git = "https://github.com/permissionlessweb/bs-nfts", rev = "1e50abdac4517bcdd5e03491589bdba6929806cf" } 
btsg-account                 = { path = "packages/btsg-account" }
cosmwasm-schema              = "2.2.0"
cosmwasm-std = { version = "2.2.0", features = [
  "cosmwasm_1_4",
  "cosmwasm_2_0",
] }
cw2 = "2.0.0"
cw-orch = "0.26.0"
cw-orch-core = "1.2.4"
cw-ownable = "2.1.0"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
subtle-encoding = { version = "0.5.1", features = ["bech32-preview"] }
thiserror = { version = "1.0.58" }