[workspace] 
members = [ 
    "contracts/bs721-account",
    "contracts/bs721-account-minter",
    "contracts/bs721-account-marketplace",
    "packages/*",
    # "scripts",
    ]
# exclude = [
#   "scripts"
# ]

resolver = "2"

[workspace.package]
version = "0.1.0"
authors = [
  "Hard-nett <hardnettt@proton.me>",
]
edition = "2021"
homepage   = "https://bitsong.io"
repository = "https://github.com/bitsongofficial/bs-accounts"
license    = "Apache-2.0"

[workspace.dependencies]
bs721                        = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "b43c7f91adf74e458f120d91db2ddab24c441d98" }
bs721-base                   = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "b43c7f91adf74e458f120d91db2ddab24c441d98"}
btsg-account = { path = "packages/btsg-account", version = "0.1.0" }
cosmwasm-schema = "1.5.7"
cosmwasm-std = { version = "1.5.7", features = [
  "cosmwasm_1_4",
] }
cw2 = "1.1.2"
cw721  = "0.18.0"
cw721-base =  { version = "0.18.0", features = ["library"] }
cw-controllers = "1.1.2"
cw-orch = "0.24.1"
cw-orch-core = "1.2.4"
cw-ownable  = "0.5.1"
cw-storage-plus = "1.2.0"
cw-utils = "1.0.3"
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
subtle-encoding = { version = "0.5.1", features = ["bech32-preview"] }
thiserror = { version = "1.0.58" }