[workspace]
members  = ["packages/*", "contracts/*","scripts"]
ignore = ["scripts"]
resolver = "2"

[workspace.package]
version    = "0.1.0-rc1"
edition    = "2021"
homepage   = "https://bitsong.io"
repository = "https://github.com/bitsongofficial/bs-accounts"
license    = "Apache-2.0"


[workspace.dependencies]
anyhow                       = { version = "1.0" }
bs721                        = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "b43c7f91adf74e458f120d91db2ddab24c441d98" }
bs721-base                   = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "b43c7f91adf74e458f120d91db2ddab24c441d98"}
bs721-account                = { version = "0.1.0-alpha.1", path = "./contracts/bs721-account",  features = ["library"] }
bs721-account-minter         = { version = "0.1.0-alpha.1", path = "./contracts/account-minter",  features = ["library"] }
bs721-account-marketplace    = { version = "0.1.0-alpha.1", path = "./contracts/account-market", features = ["library"] }
btsg-account                 = { version = "0.1.0-rc1", path = "./packages/btsg-account" }
btsg-account-marketplace     = { version = "0.1.0-rc1", path = "./packages/account-market" }
bs-controllers               = { version = "0.1.0-rc1", path = "./packages/controllers" }
btsg-cw-orch                 = { version = "0.1.0-rc1", path = "./packages/cw-orch" }
cosmwasm-schema              = "1.1.5"
cosmwasm-std                 = "1.1.5"
cw-controllers               = { version = "1.1.2" }
cw2                          = "1.1"
cw20                         = "0.16.0"
cw721                        = "0.18.0"
cw721-base                   = "0.18.0"
cw-multi-test                = "1.1.0"
cw-orch                      = "0.24.1"
cw-ownable                   = "0.5.1"
cw-storage-macro             = "1.2.0"
cw-storage-plus              = "1.2.0" 
cw-utils                     = "0.16.0"
schemars                     = "0.8.10"
semver                       = "1.0"
serde                        = { version = "1.0.140", default-features = false, features = ["derive"] }
thiserror                    = "1.0.31"
url                          = "2.2.2"

[profile.release.package.bs721-account-minter ]
codegen-units = 1
incremental   = false

[profile.release.package.bs721-account ]
codegen-units = 1
incremental   = false

[profile.release.package.bs721-account-marketplace]
codegen-units = 1
incremental   = false

[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
opt-level        = 3
debug            = false
debug-assertions = false