[workspace] 
members = [ 
    "contracts/bs721-account",
    "contracts/bs721-account-minter",
    "packages/*",
    "scripts",
    ]
# exclude = [
#   "scripts".
# ]

# Enable the version 2 feature resolver, which avoids unifying features for targets that are not being built
#
# Critically this prevents dev-dependencies from enabling features even when not building a target that
# uses dev-dependencies, e.g. the library crate. This in turn ensures that we can catch invalid feature
# flag combinations that would otherwise only surface in dependent crates
#
# Reference - https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
# See - https://github.com/apache/arrow-rs/pull/1822/files
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = [
  "Hard-nett <hardnettt@proton.me>",
]
edition = "2021"

[workspace.dependencies]
bs721                        = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "b43c7f91adf74e458f120d91db2ddab24c441d98" }
bs721-base                   = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "b43c7f91adf74e458f120d91db2ddab24c441d98"}
btsg-account = { path = "packages/btsg-account" }
cosmwasm-schema = "1.5.7"
cosmwasm-std = { version = "1.5.7", features = [
  "cosmwasm_1_4",
] }
cw2 = "1.1.2"
cw721  = "0.18.0"
cw721-base =  { version = "0.18.0", features = ["library"] }
cw-controllers = "1.1.2"
cw-orch = "0.25.0"
cw-orch-core = "1.2.4"
cw-ownable                = "0.5.1"
cw-storage-plus = "1.2.0"
cw-utils = "1.0.3"
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
subtle-encoding = { version = "0.5.1", features = ["bech32-preview"] }
thiserror = { version = "1.0.58" }