[package]
name = "btsg-cw-orch"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch.workspace = true
cosmwasm-std.workspace = true
serde.workspace     = true
bs721-account = { version = "0.1.0", path = "../../contracts/bs721-account" }
btsg-account = { version = "0.1.0", path = "../btsg-account" }
bs721-account-marketplace    = { version = "0.1.0", path = "../../contracts/bs721-account-marketplace"  }
bs721-account-minter = { version = "0.1.0", path = "../../contracts/bs721-account-minter" }

