[alias]
wasm = "build --release --lib --target wasm32-unknown-unknown"
unit-test = "test --lib"
schema = "run --bin schema"
integration-test = "test --lib integration_tests"
coverage = 'llvm-cov --html --open --workspace --exclude ownership-verifier --exclude account-registry-middleware --ignore-filename-regex "manual_deploy"'
