[package]
name        = "bs721-account-marketplace"
authors     = ["Shane Vitarana <s@noreply.publicawesome.com>"]
description = "Bitsong Profile Marketplace Smart Contract"
license     = "BUSL-1.1"
version     = { workspace = true }
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
bs721            = { workspace = true }
bs721-base       = { workspace = true, features = ["library"] }
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }
cw2              = { workspace = true }
cw-storage-plus  = { workspace = true }
cw-storage-macro = { workspace = true }
cw-utils         = { workspace = true }
cw-orch          = { workspace = true }
cw-ownable       = { workspace = true }
schemars         = { workspace = true }
semver           = { workspace = true }
serde            = { workspace = true }
btsg-account     = { workspace = true }
bs-controllers   = { workspace = true }
thiserror        = { workspace = true }

[dev-dependencies]
cw-multi-test    = { workspace = true }
bs721            = { workspace = true }
