[package]
name = "btsg-account"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-ownable   = { workspace = true }
sha2         = { workspace = true }
bech32       = { workspace = true }

ecdsa = "0.16.2"             
ripemd       = { version = "0.1.3",  default-features = false }
hex = { version = "0.4", features = ["serde"] }
hex-literal = "0.4.1"
k256 = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
cosmwasm-crypto  = { workspace = true,  default-features = false }

  
abstract-std  = { workspace = true }
bs-controllers = { workspace = true }
cw-orch    = { workspace = true }