[package]
name = "btsg-account"
authors = ["Shane Vitarana <s@noreply.publicawesome.com>",]
description = "Rust definition of name service metadata, used by Bitsong Accounts."
version  = { workspace = true }
exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-ownable   = { workspace = true }
cosmwasm-schema = "1.5.7"
abstract-std = "0.26.0"
bs-controllers = { workspace = true }
cw-orch = "0.25.0"