[package]
name = "btsg-account"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bs-controllers = { workspace = true }
cosmwasm-std    = { workspace = true }
cosmwasm-crypto = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-ownable      = { workspace = true }
ecdsa           = { workspace = true }
sha2            = { workspace = true }
bech32          = { workspace = true }
ripemd          = { workspace = true }
k256            = { workspace = true }
