[package]
name = "btsg-account"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-ownable   = { workspace = true }
sha2         = { workspace = true }
bech32       = { workspace = true }
ripemd       = { version = "0.1.3",  default-features = false }
cosmwasm-crypto  = { version = "2.1.4",  default-features = false }

cosmwasm-schema = "1.5.7"
abstract-std = "0.26.0"
bs-controllers = { workspace = true }
cw-orch = "0.25.0"