[package]
name = "btsg-account"
authors = ["Shane Vitarana <s@noreply.publicawesome.com>",]
description = "Rust definition of name service metadata, used by Bitsong Accounts."
version     = { workspace = true }
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw-orch =  { workspace = true }
cosmwasm-schema = { workspace = true }
cw-controllers  = { workspace = true }
cw-storage-macro  = { workspace = true }
cw-storage-plus  = { workspace = true }
bs-controllers  = { workspace = true }
bs721  = { workspace = true }
bs721-base  = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }