[package]
name = "btsg-account-scripts"
edition    = { workspace = true }
license    = { workspace = true } 
repository = { workspace = true }
version    = { workspace = true }

[dependencies]
btsg-auth                     = { workspace = true }
btsg-irl                      = { workspace = true }
btsg-wavs                     = { workspace = true }

cosmos-sdk-proto              = { workspace = true }
cosmwasm-crypto               = { workspace = true }
cosmwasm-schema               = { workspace = true }
cosmwasm-std                  = { workspace = true }
anyhow                        = { version = "1" }
clap                          = { version = "4.0.32", features = ["derive"] }
cw-orch                       = { workspace = true, features = ["daemon"] }
cw-ownable                    = { workspace = true }
ecdsa                         = { version = "0.16.2" }
env_logger                    = { version = "0.10.0" }
k256                          = { version = "0.13.3", default-features = false, features = ["ecdsa"] }
serde                         = { version = "1.0.140", default-features = false, features = ["derive"] }
log                           = { version = "0.4.22" }
reqwest                       = { version = "0.11.9" }
sha2                          = { workspace = true }
tokio                         = { version = "1.39.3", features = [] }

[dev-dependencies]


# Cargo CLI commands
[[bin]]
name = "deploy"
path = "src/bin/manual_deploy.rs"