[package]
name = "scripts"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/bitsongofficial/bs-accounts"
version.workspace = true

[dependencies]
cw721  = "0.18.0"
cw721-base =  { version = "0.18.0" }
bs721-base                   = { git = "https://github.com/permissionlessweb/bs-nfts", rev = "b43c7f91adf74e458f120d91db2ddab24c441d98"}
btsg-account               = { path = "../packages/btsg-account", version = "0.1.0" }
bs721-account              = { path = "../contracts/bs721-account", version = "0.1.0" }
bs721-account-minter       = { path = "../contracts/bs721-account-minter", version = "0.1.0" }
bs721-account-marketplace       = { path = "../contracts/bs721-account-marketplace", version = "0.1.0" }
cosmwasm-std = { version = "1.5.7", features = [
  "cosmwasm_1_4",
  # Enable this if you only deploy to chains that have CosmWasm 2.0 or higher
  # "cosmwasm_2_0",
] }

dotenv                     = { version = "0.15.0" }

# Abstract Framework and CW-Orchestrator Dependencies
abstract-std = "0.23.0"
abstract-client = { version = "0.23.0",  features = ["interchain"] }
abstract-interface = "0.23.1"
anyhow = "1"
clap = { version = "4.0.32", features = ["derive"] }
cw-orch-polytone = { package = "abstract-cw-orch-polytone", version = "4.0.0" }
cw-orch-interchain = { version = "0.3.0",  features = ["daemon"] }
cw-orch-clone-testing = { version = "0.6.4" }
cw-orch   = { version = "0.24.1", features = ["daemon"] }
dirs = "5.0.1"
cw-ownable  = "0.5.1"
env_logger = "0.10.0"
log = "0.4.22"
polytone = { package = "abstract-polytone", version = "1.0.5" }
polytone-note = { package = "abstract-polytone-note", version = "3.0.0" }
pretty_env_logger          = { version = "0.5.0" }
reqwest = { version = "0.11.9" }
serde                        = { version = "1.0.140", default-features = false, features = ["derive"] }
serde_json = "1.0.79"
tokio = "1.39.3"
cw-orch-interchain-core = "0.5.0"

[dev-dependencies]

# Cargo CLI commands
[[bin]]
name = "deploy"
path = "src/bin/manual_deploy.rs"