/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  admin?: string | null;
  base_price: Uint128;
  collection_code_id: number;
  marketplace_addr: string;
  max_account_length: number;
  min_account_length: number;
  verifier?: string | null;
}
export type ExecuteMsg = {
  mint_and_list: {
    account: string;
  };
} | {
  update_admin: {
    admin?: string | null;
  };
} | {
  pause: {
    pause: boolean;
  };
} | {
  update_config: {
    config: Config;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface Config {
  public_mint_start_time: Timestamp;
}
export type QueryMsg = {
  admin: {};
} | {
  collection: {};
} | {
  params: {};
} | {
  config: {};
};
export interface AdminResponse {
  admin?: string | null;
}
export type Addr = string;
export interface SudoParams {
  base_price: Uint128;
  max_account_length: number;
  min_account_length: number;
}